FROM node:18-alpine
WORKDIR /app
ENV CI=true
RUN npm install -g pnpm pm2

#COPY frontend/package.json frontend/.npmrc pnpm-lock.yaml pnpm-workspace.yaml ./

COPY . .
RUN pnpm --filter ./frontend install --frozen-lockfile
RUN pnpm --filter ./frontend build
WORKDIR /app/frontend

CMD ["pm2-runtime", "./ecosystem.config.cjs"]