/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor' | 'user';
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resource".
 */
export interface Resource {
  id: string;
  name: string;
  description?: {
    [k: string]: unknown;
  }[];
  immaterial?: boolean;
  relative?: boolean;
  parent?: string | Resource;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "action".
 */
export interface Action {
  id: string;
  name: string;
  tags?: string[] | Tag[];
  description?: {
    [k: string]: unknown;
  }[];
  inputs: {
    condition?: 'and' | 'or';
    ports?:
      | (
          | {
              value: string;
              relationTo: 'product';
            }
          | {
              value: string;
              relationTo: 'action';
            }
        )[]
      | (
          | {
              value: Product;
              relationTo: 'product';
            }
          | {
              value: Action;
              relationTo: 'action';
            }
        )[];
    groups: {
      condition?: 'and' | 'or';
      ports?:
        | (
            | {
                value: string;
                relationTo: 'product';
              }
            | {
                value: string;
                relationTo: 'action';
              }
          )[]
        | (
            | {
                value: Product;
                relationTo: 'product';
              }
            | {
                value: Action;
                relationTo: 'action';
              }
          )[];
      groups: {
        condition?: 'and' | 'or';
        ports?:
          | (
              | {
                  value: string;
                  relationTo: 'product';
                }
              | {
                  value: string;
                  relationTo: 'action';
                }
            )[]
          | (
              | {
                  value: Product;
                  relationTo: 'product';
                }
              | {
                  value: Action;
                  relationTo: 'action';
                }
            )[];
        groups: {
          condition?: 'and' | 'or';
          ports?:
            | (
                | {
                    value: string;
                    relationTo: 'product';
                  }
                | {
                    value: string;
                    relationTo: 'action';
                  }
              )[]
            | (
                | {
                    value: Product;
                    relationTo: 'product';
                  }
                | {
                    value: Action;
                    relationTo: 'action';
                  }
              )[];
          id?: string;
        }[];
        id?: string;
      }[];
      id?: string;
    }[];
  };
  outputs: {
    condition?: 'and' | 'or';
    ports?:
      | (
          | {
              value: string;
              relationTo: 'product';
            }
          | {
              value: string;
              relationTo: 'action';
            }
        )[]
      | (
          | {
              value: Product;
              relationTo: 'product';
            }
          | {
              value: Action;
              relationTo: 'action';
            }
        )[];
    groups: {
      condition?: 'and' | 'or';
      ports?:
        | (
            | {
                value: string;
                relationTo: 'product';
              }
            | {
                value: string;
                relationTo: 'action';
              }
          )[]
        | (
            | {
                value: Product;
                relationTo: 'product';
              }
            | {
                value: Action;
                relationTo: 'action';
              }
          )[];
      groups: {
        condition?: 'and' | 'or';
        ports?:
          | (
              | {
                  value: string;
                  relationTo: 'product';
                }
              | {
                  value: string;
                  relationTo: 'action';
                }
            )[]
          | (
              | {
                  value: Product;
                  relationTo: 'product';
                }
              | {
                  value: Action;
                  relationTo: 'action';
                }
            )[];
        groups: {
          condition?: 'and' | 'or';
          ports?:
            | (
                | {
                    value: string;
                    relationTo: 'product';
                  }
                | {
                    value: string;
                    relationTo: 'action';
                  }
              )[]
            | (
                | {
                    value: Product;
                    relationTo: 'product';
                  }
                | {
                    value: Action;
                    relationTo: 'action';
                  }
              )[];
          id?: string;
        }[];
        id?: string;
      }[];
      id?: string;
    }[];
  };
  timeUnit?: 'millisecond' | 'second' | 'minute' | 'hour' | 'day' | 'week' | 'month' | 'year';
  estimatedDuration?: number;
  resource?: string | Resource;
  moving?: boolean;
  resourceTo?: string | Resource;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tag".
 */
export interface Tag {
  id: string;
  name?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
  id: string;
  name: string;
  tags?: string[] | Tag[];
  description?: {
    [k: string]: unknown;
  }[];
  providers: {
    url?: string;
    price?: number;
    id?: string;
  }[];
  variables: (
    | {
        freeValue?: boolean;
        options: {
          value?: string;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'text';
      }
    | {
        freeValue?: boolean;
        unit?: string;
        options: {
          value?: number;
          id?: string;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'numeric';
      }
  )[];
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "item".
 */
export interface Item {
  id: string;
  virtual?: boolean;
  validity: {
    start?: string;
    end?: string;
  };
  product: string | Product;
  createdAt: string;
  updatedAt: string;
}
